In [56]:
import numpy as np
A=np.array([1,2,3])
A

array([1, 2, 3])

In [57]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
A+A

array([2, 4, 6])

In [59]:
A*A

array([1, 4, 9])

In [60]:
B=np.array([[1],[2],[3]])#IF WE WANT A COLUMN
B


array([[1],
       [2],
       [3]])

In [61]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(0,101,2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [63]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [64]:
np.ones((4,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [65]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [66]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [67]:
data = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [68]:
data[1]

array([5, 6, 7, 8])

In [69]:
data[1, 3]

8

In [70]:
np.random.rand(2,2)

array([[0.29787552, 0.32570763],
       [0.80601028, 0.18195119]])

In [71]:
np.random.randn(5,5)

array([[ 3.92305204e-01,  8.58538673e-01,  7.36020307e-01,
         1.47457436e+00, -6.13066423e-01],
       [ 1.26073178e+00, -1.98202826e-01, -1.14404597e+00,
        -4.91119315e-01,  1.87997929e+00],
       [-1.48558363e-01,  1.25754324e-01, -3.12254805e-01,
         7.34071338e-01, -3.09500348e-01],
       [-1.12499472e+00,  4.76880066e-01, -9.83380608e-04,
        -6.01264607e-02, -6.06993223e-01],
       [-1.28184206e+00,  1.73748576e+00,  1.88216588e+00,
        -2.78837518e-01, -1.73990623e+00]])

In [72]:
import pandas as pd

In [73]:
ser = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [74]:
df = pd.DataFrame(np.random.randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
A  1.054745  2.077269 -1.213461  0.745305
B -0.844660 -1.595629 -0.719807 -0.176041
C -0.659687 -0.583473  0.563964 -0.553618
D  1.492084  0.424138  0.108923 -0.310039
E -0.109873  0.705712 -0.550844  0.582439

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   W       5 non-null      float64
 1   X       5 non-null      float64
 2   Y       5 non-null      float64
 3   Z       5 non-null      float64
dtypes: float64(4)
memory usage: 200.0+ bytes


In [76]:
df.head()

W         X         Y         Z
A  1.054745  2.077269 -1.213461  0.745305
B -0.844660 -1.595629 -0.719807 -0.176041
C -0.659687 -0.583473  0.563964 -0.553618
D  1.492084  0.424138  0.108923 -0.310039
E -0.109873  0.705712 -0.550844  0.582439

In [77]:
df['new'] = df['W'] + df['Y']
df

W         X         Y         Z       new
A  1.054745  2.077269 -1.213461  0.745305 -0.158716
B -0.844660 -1.595629 -0.719807 -0.176041 -1.564467
C -0.659687 -0.583473  0.563964 -0.553618 -0.095723
D  1.492084  0.424138  0.108923 -0.310039  1.601007
E -0.109873  0.705712 -0.550844  0.582439 -0.660717

In [78]:
df.drop('new',axis=1)
df

W         X         Y         Z       new
A  1.054745  2.077269 -1.213461  0.745305 -0.158716
B -0.844660 -1.595629 -0.719807 -0.176041 -1.564467
C -0.659687 -0.583473  0.563964 -0.553618 -0.095723
D  1.492084  0.424138  0.108923 -0.310039  1.601007
E -0.109873  0.705712 -0.550844  0.582439 -0.660717

In [79]:
df.drop('new',axis=1, inplace = True ) # inplace = False by default 永久置換
df

W         X         Y         Z
A  1.054745  2.077269 -1.213461  0.745305
B -0.844660 -1.595629 -0.719807 -0.176041
C -0.659687 -0.583473  0.563964 -0.553618
D  1.492084  0.424138  0.108923 -0.310039
E -0.109873  0.705712 -0.550844  0.582439

In [80]:
df.rename(index={'A':'CA', 'B':'NY', 'C':'WY', 'D':'OR', 'E':'CO'}, inplace=True)
df

W         X         Y         Z
CA  1.054745  2.077269 -1.213461  0.745305
NY -0.844660 -1.595629 -0.719807 -0.176041
WY -0.659687 -0.583473  0.563964 -0.553618
OR  1.492084  0.424138  0.108923 -0.310039
CO -0.109873  0.705712 -0.550844  0.582439

In [81]:
df['V'] = [1, 2, np.nan, np.nan, 5]
df

W         X         Y         Z    V
CA  1.054745  2.077269 -1.213461  0.745305  1.0
NY -0.844660 -1.595629 -0.719807 -0.176041  2.0
WY -0.659687 -0.583473  0.563964 -0.553618  NaN
OR  1.492084  0.424138  0.108923 -0.310039  NaN
CO -0.109873  0.705712 -0.550844  0.582439  5.0

In [82]:
df.isnull()

W      X      Y      Z      V
CA  False  False  False  False  False
NY  False  False  False  False  False
WY  False  False  False  False   True
OR  False  False  False  False   True
CO  False  False  False  False  False

In [83]:
df.isnull().sum()

W    0
X    0
Y    0
Z    0
V    2
dtype: int64

In [84]:
df.isnull().sum().sum()

2

In [85]:
df.dropna()

W         X         Y         Z    V
CA  1.054745  2.077269 -1.213461  0.745305  1.0
NY -0.844660 -1.595629 -0.719807 -0.176041  2.0
CO -0.109873  0.705712 -0.550844  0.582439  5.0

In [86]:
df.fillna(value = 'replace')

W         X         Y         Z        V
CA  1.054745  2.077269 -1.213461  0.745305        1
NY -0.844660 -1.595629 -0.719807 -0.176041        2
WY -0.659687 -0.583473  0.563964 -0.553618  replace
OR  1.492084  0.424138  0.108923 -0.310039  replace
CO -0.109873  0.705712 -0.550844  0.582439        5

作業一

In [87]:
hf = pd.DataFrame(data=[[90, 60, 33], [50, 70, 75], [70, 90, 88], [80, 50, 60]],columns='Math English History'.split(),index='Simon Allen Jimmy Peter'.split())
hf#第一題

Math  English  History
Simon    90       60       33
Allen    50       70       75
Jimmy    70       90       88
Peter    80       50       60

In [88]:
bf=hf[hf['English']>85]
cf=bf[bf['Math']>60]
cf#第二題

Math  English  History
Jimmy    70       90       88

In [89]:
hf.mean()#第三題

Math       72.5
English    67.5
History    64.0
dtype: float64

In [90]:
hf.sort_values(by=['Math'])#第四題

Math  English  History
Allen    50       70       75
Jimmy    70       90       88
Peter    80       50       60
Simon    90       60       33

In [91]:
hf.sort_values(by=['English'])

Math  English  History
Peter    80       50       60
Simon    90       60       33
Allen    50       70       75
Jimmy    70       90       88

In [92]:
hf.sort_values(by=['History'])

Math  English  History
Simon    90       60       33
Peter    80       50       60
Allen    50       70       75
Jimmy    70       90       88

In [93]:
hf.rank(ascending=False)#第二種方法

Math  English  History
Simon   1.0      3.0      4.0
Allen   4.0      2.0      2.0
Jimmy   3.0      1.0      1.0
Peter   2.0      4.0      3.0

In [94]:
hf['Gender'] = ['M','F','M','M']
hf#第五題

Math  English  History Gender
Simon    90       60       33      M
Allen    50       70       75      F
Jimmy    70       90       88      M
Peter    80       50       60      M

In [95]:
result = pd.value_counts(['M','F','M','M'])
result#第六題

M    3
F    1
dtype: int64

In [96]:
hf['mean']=hf.mean(1)
hf#第七題

Math  English  History Gender       mean
Simon    90       60       33      M  61.000000
Allen    50       70       75      F  65.000000
Jimmy    70       90       88      M  82.666667
Peter    80       50       60      M  63.333333

In [97]:
hf.sort_values(by=['mean'])#第八題

Math  English  History Gender       mean
Simon    90       60       33      M  61.000000
Peter    80       50       60      M  63.333333
Allen    50       70       75      F  65.000000
Jimmy    70       90       88      M  82.666667

In [98]:
hf.rank(ascending=False)#第二種方法

Math  English  History  Gender  mean
Simon   1.0      3.0      4.0     2.0   4.0
Allen   4.0      2.0      2.0     4.0   2.0
Jimmy   3.0      1.0      1.0     2.0   1.0
Peter   2.0      4.0      3.0     2.0   3.0